name: Xcode - iOS Simulator Build & Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: iOS Simulator Build
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Latest Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Show available iOS simulators
        run: xcrun simctl list devices

      - name: Build for iOS Simulator ONLY
        run: |
          # Detect workspace or project
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then
            filetype_parameter="workspace"
            file_to_build="`ls -A | grep -i \\.xcworkspace\$`"
          else
            filetype_parameter="project"
            file_to_build="`ls -A | grep -i \\.xcodeproj\$`"
          fi
          
          scheme="Holdings_Assignment"

          echo "Building scheme: $scheme"
          echo "Using $filetype_parameter: $file_to_build"

          # Get latest available iOS simulator dynamically
          destination=$(xcrun simctl list devices available | grep -m 1 "iPhone" | awk -F'[()]' '{print $2}')

          echo "Using destination: $destination"

          xcodebuild clean build analyze \
            -scheme "$scheme" \
            -"$filetype_parameter" "$file_to_build" \
            -destination "platform=iOS Simulator,id=$destination" \
            -skipUnavailableActions \
            -quiet \
            | xcpretty && exit ${PIPESTATUS[0]}
