name: Xcode - Build and Analyze (iOS Simulator Only)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Analyze on iOS Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: Explicitly pick the latest stable Xcode
      - name: Select Latest Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      # Optional: Show available simulators (for debug)
      - name: List Available iOS Simulators
        run: xcrun simctl list devices

      - name: Build and Analyze (iPhone Simulator only)
        run: |
          # Detect whether workspace or project
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then
            filetype_parameter="workspace"
            file_to_build="`ls -A | grep -i \\.xcworkspace\$`"
          else
            filetype_parameter="project"
            file_to_build="`ls -A | grep -i \\.xcodeproj\$`"
          fi
          
          # Replace with your actual scheme name
          scheme="Holdings_Assignment"

          echo "Building scheme: $scheme"
          echo "Using $filetype_parameter: $file_to_build"

          # Build & Analyze only for iOS Simulator — never My Mac
          xcodebuild clean build analyze \
            -scheme "$scheme" \
            -"$filetype_parameter" "$file_to_build" \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=18.0" \
            -skipUnavailableActions \
            | xcpretty && exit ${PIPESTATUS[0]}
