name: iOS CI - Holdings_Assignment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on iPhone Simulator
    runs-on: macos-15

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Select Xcode 16
      - name: Select Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.0"

      # 3️⃣ Create and boot iPhone simulator with available runtime
      - name: Create & Boot Simulator
        id: sim
        run: |
          echo "📱 Listing available runtimes:"
          xcrun simctl list runtimes

          # Find latest available iOS runtime identifier
          RUNTIME=$(xcrun simctl list runtimes | grep "iOS" | grep -v unavailable | tail -1 | awk -F '[()]' '{print $2}')
          echo "✅ Using runtime: $RUNTIME"

          DEVICE_TYPE="com.apple.CoreSimulator.SimDeviceType.iPhone-16-Pro"
          echo "Creating simulator..."
          DEVICE_ID=$(xcrun simctl create "iPhone-16-Pro-CI" "$DEVICE_TYPE" "$RUNTIME")
          echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV

          echo "Booting simulator..."
          xcrun simctl boot "$DEVICE_ID" || true
          xcrun simctl list devices

      # 4️⃣ Build
      - name: Build app for simulator
        run: |
          echo "🏗️ Building Holdings_Assignment for simulator..."
          xcodebuild \
            -scheme "Holdings_Assignment" \
            -sdk iphonesimulator \
            -destination "id=${DEVICE_ID}" \
            clean build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=YES \
            -allowProvisioningUpdates

      # 5️⃣ Optional: Test
      - name: Run tests
        run: |
          echo "🧪 Running tests..."
          xcodebuild \
            -scheme "Holdings_Assignment" \
            -sdk iphonesimulator \
            -destination "id=${DEVICE_ID}" \
            test \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      # 6️⃣ Optional: Upload Derived Data
      - name: Upload Derived Data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: DerivedData
          path: ~/Library/Developer/Xcode/DerivedData/
