name: Xcode - Build and Analyze (iOS Simulator)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Analyze on iOS Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Latest Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Show Available Simulators
        run: xcrun simctl list devices

      - name: Build and Analyze for iPhone Simulator
        run: |
          # Detect workspace or project
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then
            filetype_parameter="workspace"
            file_to_build="`ls -A | grep -i \\.xcworkspace\$`"
          else
            filetype_parameter="project"
            file_to_build="`ls -A | grep -i \\.xcodeproj\$`"
          fi
          
          # Set your actual scheme name here
          scheme="Holdings_Assignment"

          echo "Building scheme: $scheme"
          echo "Using $filetype_parameter: $file_to_build"

          # Clean + Build + Analyze for iOS 18 simulator
          xcodebuild clean build analyze \
            -scheme "$scheme" \
            -"$filetype_parameter" "$file_to_build" \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=26.0" \
            | xcpretty && exit ${PIPESTATUS[0]}
