name: iOS Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test iOS App
    runs-on: macos-15  # macOS 15 Sonoma (Xcode 16 runner)
    timeout-minutes: 30

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v4

      - name: 🧰 Set up Xcode
        run: |
          sudo xcode-select -s "/Applications/Xcode_16.app"
          xcodebuild -version

      - name: 🔍 Find latest iOS runtime
        id: find-runtime
        run: |
          RUNTIME=$(xcrun simctl list runtimes iOS -j | jq -r '.runtimes[] | select(.isAvailable == true) | .identifier' | tail -1)
          if [ -z "$RUNTIME" ]; then
            echo "❌ No available iOS simulator runtimes found!"
            exit 1
          fi
          echo "✅ Using runtime: $RUNTIME"
          echo "RUNTIME=$RUNTIME" >> $GITHUB_ENV

      - name: 📱 Create iPhone simulator
        id: create-sim
        run: |
          DEVICE_NAME="iPhone 16 Pro"
          echo "📱 Creating simulator: $DEVICE_NAME"
          DEVICE_ID=$(xcrun simctl create "TestDevice" "$DEVICE_NAME" "$RUNTIME" || true)
          if [ -z "$DEVICE_ID" ]; then
            echo "⚠️ Fallback to existing simulator"
            DEVICE_ID=$(xcrun simctl list devices -j | jq -r '.devices[][] | select(.isAvailable == true and .name | contains("iPhone")) | .udid' | head -1)
          fi
          if [ -z "$DEVICE_ID" ]; then
            echo "❌ Failed to create or find any available simulator!"
            exit 1
          fi
          echo "✅ Using simulator: $DEVICE_ID"
          echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV

      - name: ▶️ Boot simulator
        run: |
          xcrun simctl boot "$DEVICE_ID" || true
          xcrun simctl bootstatus "$DEVICE_ID" -b

      - name: 🏗️ Build for testing
        run: |
          xcodebuild \
            -scheme Holdings_Assignment \
            -project Holdings_Assignment.xcodeproj \
            -destination "platform=iOS Simulator,id=$DEVICE_ID" \
            -configuration Debug \
            clean build-for-testing \
            | xcpretty

      - name: 🧪 Run tests
        run: |
          xcodebuild \
            -scheme Holdings_Assignment \
            -project Holdings_Assignment.xcodeproj \
            -destination "platform=iOS Simulator,id=$DEVICE_ID" \
            test-without-building \
            | xcpretty
