name: iOS CI - Holdings_Assignment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on iPhone Simulator
    runs-on: macos-15   # Includes Xcode 16

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Set up Xcode 16
      - name: Select Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.0"

      # 3️⃣ Create and boot a simulator manually
      - name: Create & Boot iPhone Simulator
        run: |
          echo "Available runtimes:"
          xcrun simctl list runtimes
          
          echo "Creating simulator..."
          DEVICE_ID=$(xcrun simctl create "iPhone-16-Pro" "com.apple.CoreSimulator.SimDeviceType.iPhone-16-Pro" "com.apple.CoreSimulator.SimRuntime.iOS-18-0")

          echo "Booting simulator..."
          xcrun simctl boot "$DEVICE_ID"
          xcrun simctl list devices
          
          echo "Simulator ready."

      # 4️⃣ Clean & Build
      - name: Build for iPhone Simulator
        run: |
          xcodebuild \
            -scheme "Holdings_Assignment" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone-16-Pro,OS=18.0' \
            clean build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=YES \
            -allowProvisioningUpdates

      # 5️⃣ (Optional) Run Unit Tests
      - name: Run Tests
        run: |
          xcodebuild \
            -scheme "Holdings_Assignment" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone-16-Pro,OS=18.0' \
            test \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      # 6️⃣ (Optional) Upload DerivedData
      - name: Upload Derived Data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: DerivedData
          path: ~/Library/Developer/Xcode/DerivedData/
