name: iOS Build (iPhone 17 only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build for iOS Simulator (iPhone 17, iOS 26)
    runs-on: macos-15  # ✅ Latest macOS image supports iOS 26 SDK

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.0"

      - name: List available simulators (for debug)
        run: xcrun simctl list devices

      - name: Build for iPhone 17 simulator only
        run: |
          xcodebuild \
            -scheme "Holdings_Assignment" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 17,OS=26.0.1' \
            clean build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
