name: iOS CI Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: 🧩 Checkout Repository
        uses: actions/checkout@v4

      - name: 🛠️ Select Xcode 16
        run: |
          sudo xcode-select -s /Applications/Xcode_16.app
          echo "✅ Xcode selected:"
          xcodebuild -version

      - name: 📱 Prepare iOS Simulator
        run: |
          echo "📱 Listing available runtimes:"
          xcrun simctl list runtimes

          # Extract the latest available iOS runtime identifier (skip unavailable)
          RUNTIME=$(xcrun simctl list runtimes | grep "iOS" | grep -v unavailable | grep -E "com.apple.CoreSimulator.SimRuntime.iOS-[0-9]+" | tail -1 | awk '{print $NF}' | tr -d '()')
          echo "✅ Using runtime: $RUNTIME"

          DEVICE_TYPE="com.apple.CoreSimulator.SimDeviceType.iPhone-16-Pro"
          echo "📱 Creating simulator..."
          DEVICE_ID=$(xcrun simctl create "iPhone-16-Pro-CI" "$DEVICE_TYPE" "$RUNTIME")
          echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV

          echo "🚀 Booting simulator..."
          xcrun simctl boot "$DEVICE_ID" || true
          xcrun simctl list devices

      - name: 🧱 Build iOS App
        run: |
          DERIVED_DATA_PATH="$PWD/DerivedData"
          echo "🏗️ Building Holdings_Assignment for simulator..."
          xcodebuild \
            -scheme "Holdings_Assignment" \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,id=${DEVICE_ID}" \
            -derivedDataPath "$DERIVED_DATA_PATH" \
            clean build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -quiet

          echo "✅ Build completed successfully. Derived data stored at: $DERIVED_DATA_PATH"

      - name: 🧪 Run Tests
        run: |
          DERIVED_DATA_PATH="$PWD/DerivedData"
          echo "🧪 Running Unit/UI Tests on simulator..."
          xcodebuild \
            test \
            -scheme "Holdings_Assignment" \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,id=${DEVICE_ID}" \
            -derivedDataPath "$DERIVED_DATA_PATH" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -quiet

          echo "✅ Tests completed successfully."

      - name: 🧹 Cleanup Simulator
        if: always()
        run: |
          echo "🧹 Shutting down and deleting simulator..."
          xcrun simctl shutdown "$DEVICE_ID" || true
          xcrun simctl delete "$DEVICE_ID" || true
          echo "🧼 Cleanup complete."
