name: Xcode - Build and Test (iOS Simulator)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.app

      - name: Show available runtimes
        run: |
          echo "📱 Listing available runtimes:"
          xcrun simctl list runtimes

      - name: Create and boot iPhone simulator
        id: simulator
        run: |
          echo "🔍 Finding latest available iOS runtime identifier..."
          # Extract proper runtime identifier (e.g. com.apple.CoreSimulator.SimRuntime.iOS-26-0)
          RUNTIME=$(xcrun simctl list runtimes | grep "iOS" | grep -v unavailable | tail -1 | awk '{print $NF}' | tr -d ')')
          echo "✅ Using runtime identifier: $RUNTIME"

          DEVICE_TYPE="com.apple.CoreSimulator.SimDeviceType.iPhone-16-Pro"
          echo "📱 Creating simulator..."
          DEVICE_ID=$(xcrun simctl create "iPhone-16-Pro-CI" "$DEVICE_TYPE" "$RUNTIME")
          echo "✅ Created simulator: $DEVICE_ID"
          echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV

          echo "🚀 Booting simulator..."
          xcrun simctl boot "$DEVICE_ID" || true

          echo "⌛ Waiting for simulator to finish booting..."
          xcrun simctl bootstatus "$DEVICE_ID" -b

          xcrun simctl list devices

      - name: Build and Test
        run: |
          SCHEME="Holdings_Assignment"
          echo "🏗️ Building and testing scheme: $SCHEME"
          xcodebuild \
            -scheme "$SCHEME" \
            -destination "platform=iOS Simulator,id=${DEVICE_ID}" \
            clean build test \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            | xcpretty
